// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXM3TU0VcxkLqKBF2plvwF9AT8FZxB07U',
    appId: '1:113140806715:web:710bb9dc1165372949d81e',
    messagingSenderId: '113140806715',
    projectId: 'snkrstacks',
    authDomain: 'snkrstacks.firebaseapp.com',
    storageBucket: 'snkrstacks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDssD168kt3IUOaOYwqu6jwT4JAVAMwN8A',
    appId: '1:113140806715:android:8e8eb128be92c1f149d81e',
    messagingSenderId: '113140806715',
    projectId: 'snkrstacks',
    storageBucket: 'snkrstacks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ePBk9v4J0eFzywQAwwpc8aZvefzWjyk',
    appId: '1:113140806715:ios:d53969a064be8c7549d81e',
    messagingSenderId: '113140806715',
    projectId: 'snkrstacks',
    storageBucket: 'snkrstacks.firebasestorage.app',
    iosBundleId: 'betatest.vndyDuex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ePBk9v4J0eFzywQAwwpc8aZvefzWjyk',
    appId: '1:113140806715:ios:574c5fc3275b510e49d81e',
    messagingSenderId: '113140806715',
    projectId: 'snkrstacks',
    storageBucket: 'snkrstacks.firebasestorage.app',
    iosBundleId: 'com.example.vndyDuex',
  );
}
